### ISSUE TITLE
webclient cannot available

### ISSUE THREAD

**Issue by honda6** [eherr/motion_database_server#1]
hi, can you upload the project named webclient again?

**Comment by eherr** [comment]
The repository should now be available. I also updated the server code. It is not that well tested so there might be bugs.

**Comment by honda6** [comment]
> The repository should now be available. I also updated the server code. It is not that well tested so there might be bugs.

Thanks~ i can clone it now. It is an excellent job~
Would you mind updata the mgrd code? it also canot be available.

**Comment by eherr** [comment]
Sorry we cannot make this part public yet, because we share the rights to it with some other project partner. The module mainly contains faster implementations using custom C-modules for the sampling of a statistical motion model. However, the remaining code should work also without it,
